"use client"

import { useState, useEffect, createContext, useContext } from 'react'

type Language = 'en' | 'zh'

interface LanguageContextType {
  language: Language
  setLanguage: (lang: Language) => void
  t: (key: string) => string
}

const translations = {
  en: {
    // Navigation
    'nav.dashboard': 'Dashboard',
    'nav.meme': 'Meme',
    'nav.airdrop': 'Airdrop',
    'nav.arbitrage': 'Arbitrage',
    'nav.spot': 'Spot',
    'nav.journal': 'Journal',
    'nav.tools': 'Tools',
    'nav.depin': 'DePIN',
    'nav.dao': 'DAO',
    
    // Common
    'common.appTitle': 'Web3 Dashboard',
    'common.connectWallet': 'Connect Wallet',
    'common.connected': 'Connected',
    'common.loading': 'Loading...',
    'common.search': 'Search',
    'common.filter': 'Filter',
    'common.new': 'New',
    'common.edit': 'Edit',
    'common.delete': 'Delete',
    'common.save': 'Save',
    'common.cancel': 'Cancel',
    'common.confirm': 'Confirm',
    'common.required': 'Required',
    'common.invalidAmount': 'Invalid amount',
    'common.invalidPeriod': 'Invalid period',
    'common.invalidQuorum': 'Invalid quorum',
    'common.invalidThreshold': 'Threshold must be between 50-100%',
    'common.confirmDelete': 'Confirm Delete',
    'common.deleteWarning': 'This action cannot be undone. Are you sure?',
    'common.confirmCancel': 'Confirm Cancel',
    'common.cancelWarning': 'Are you sure you want to cancel? Unsaved changes will be lost.',
    'common.actionWarning': 'Are you sure you want to proceed?',
    
    // Dashboard
    'dashboard.title': 'Dashboard',
    'dashboard.subtitle': 'Welcome to your Web3 trading hub. Monitor markets, track airdrops, and manage your portfolio.',
    'dashboard.totalPortfolio': 'Total Portfolio Value',
    'dashboard.memeCoinsTracked': 'Meme Coins Tracked',
    'dashboard.activeAirdrops': 'Active Airdrops',
    'dashboard.arbitrageOpportunities': 'Arbitrage Opportunities',
    'dashboard.marketOverview': 'Market Overview',
    'dashboard.marketOverviewDesc': 'Real-time price movements and trends',
    'dashboard.chartPlaceholder': 'Chart visualization will be implemented here',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.quickActionsDesc': 'Fast access to common tasks',
    'dashboard.checkAirdrops': 'Check Airdrops',
    'dashboard.pendingAirdrops': '8 pending',
    'dashboard.viewMemeTrends': 'View Meme Trends',
    'dashboard.memeTracked': '142 tracked',
    'dashboard.arbitrageScanner': 'Arbitrage Scanner',
    'dashboard.arbitrageOpportunitiesCount': '3 opportunities',
    
    // Meme
    'meme.title': 'Meme Coins',
    'meme.subtitle': 'Track trending meme coins and discover new opportunities',
    'meme.watchlist': 'Watchlist',
    'meme.discoverNew': 'Discover New',
    'meme.marketSummary': 'Market Summary',
    'meme.totalMarketCap': 'Total Market Cap',
    'meme.volume24h': '24h Volume',
    'meme.trendingCoins': 'Trending Coins',
    'meme.alerts': 'Alerts',
    'meme.addToWatchlist': 'Add coins to your watchlist',
    'meme.setPriceAlerts': 'Set price alerts',
    'meme.trendingMemeCoins': 'Trending Meme Coins',
    'meme.mostPopular': 'Most popular meme coins by volume and social activity',
    'meme.marketCap': 'Market Cap',
    'meme.volume': 'Volume',

    // Airdrop
    'airdrop.title': 'Airdrops',
    'airdrop.subtitle': 'Track active airdrops and claim rewards',
    'airdrop.active': 'Active',
    'airdrop.upcoming': 'Upcoming',
    'airdrop.claimed': 'Claimed',
    'airdrop.activeAirdrops': 'Active Airdrops',
    'airdrop.upcomingAirdrops': 'Upcoming Airdrops',
    'airdrop.claimedRewards': 'Claimed Rewards',
    'airdrop.totalValue': 'Total Value',
    'airdrop.thisMonth': 'This Month',
    'airdrop.checkEligibility': 'Check Eligibility',
    'airdrop.claimNow': 'Claim Now',
    'airdrop.eligibilityChecker': 'Eligibility Checker',
    'airdrop.checkEligibilityDesc': 'Verify your eligibility for active airdrops',
    'airdrop.endsIn': 'Ends in',
    'airdrop.status': 'Status',
    'airdrop.rewards': 'Rewards',

    // Arbitrage
    'arbitrage.title': 'Arbitrage',
    'arbitrage.subtitle': 'Find profitable arbitrage opportunities across DEXs',
    'arbitrage.scanner': 'Scanner',
    'arbitrage.opportunities': 'Opportunities',
    'arbitrage.settings': 'Settings',
    'arbitrage.activeOpportunities': 'Active Opportunities',
    'arbitrage.profitPotential': 'Profit Potential',
    'arbitrage.executionTime': 'Execution Time',
    'arbitrage.tradingPairs': 'Trading Pairs',
    'arbitrage.gasEstimate': 'Gas Estimate',
    'arbitrage.execute': 'Execute',
    'arbitrage.analyze': 'Analyze',
    'arbitrage.profit': 'Profit',
    'arbitrage.risk': 'Risk',
    'arbitrage.dex': 'DEX',

    // Spot
    'spot.title': 'Spot Trading',
    'spot.subtitle': 'Real-time spot trading across multiple exchanges',
    'spot.buy': 'Buy',
    'spot.sell': 'Sell',
    'spot.orderBook': 'Order Book',
    'spot.recentTrades': 'Recent Trades',
    'spot.portfolio': 'Portfolio',
    'spot.balance': 'Balance',
    'spot.available': 'Available',
    'spot.inOrders': 'In Orders',
    'spot.marketPrice': 'Market Price',
    'spot.limitPrice': 'Limit Price',
    'spot.amount': 'Amount',
    'spot.total': 'Total',
    'spot.placeOrder': 'Place Order',
    'spot.openOrders': 'Open Orders',
    'spot.orderHistory': 'Order History',

    // Tools
    'tools.title': 'Tools',
    'tools.subtitle': 'Comprehensive Web3 trading tools and utilities',
    'tools.priceAlerts': 'Price Alerts',
    'tools.portfolio': 'Portfolio Tracker',
    'tools.calculator': 'Calculator',
    'tools.news': 'News & Analysis',
    'tools.calendar': 'Event Calendar',
    'tools.research': 'Research',
    'tools.setPriceAlert': 'Set Price Alert',
    'tools.trackPortfolio': 'Track Portfolio',
    'tools.calculate': 'Calculate',
    'tools.readNews': 'Read News',
    'tools.viewCalendar': 'View Calendar',
    'tools.doResearch': 'Do Research',
    'tools.comingSoon': 'Coming Soon',
    'tools.toolInDevelopment': 'This tool is under development',
    
    // Tool Categories
    'tools.funding': 'Funding Intelligence',
    'tools.fundingDesc': 'VC data, funding rounds, and investor analysis',
    'tools.efficiency': 'Efficiency Tools', 
    'tools.efficiencyDesc': 'Batch operations, wallet management, and automation',
    'tools.solana': 'Solana Tools',
    'tools.solanaDesc': 'SPL tokens, NFTs, and program utilities',
    'tools.market': 'Market Data',
    'tools.marketDesc': 'Price monitoring, arbitrage, and liquidity analysis',
    'tools.security': 'Security Tools',
    'tools.securityDesc': 'Contract auditing, wallet security, and risk assessment',
    'tools.developer': 'Developer Tools',
    'tools.developerDesc': 'Anchor templates, RPC testing, and debugging',
    
    // Tool Status
    'tools.active': 'Active',
    'tools.beta': 'Beta',
    'tools.soon': 'Soon',
    'tools.available': 'Available',
    'tools.favorites': 'Favorites',
    'tools.recentlyUsed': 'Recently Used',
    'tools.usage': 'Usage',
    'tools.open': 'Open',
    'tools.use': 'Use Tool',

    // DePIN
    'depin.title': 'DePIN',
    'depin.subtitle': 'Decentralized Physical Infrastructure Networks',
    'depin.storage': 'Storage Networks',
    'depin.computing': 'Computing Networks',
    'depin.wireless': 'Wireless Networks',
    'depin.sensors': 'Sensor Networks',
    'depin.totalNetworks': 'Total Networks',
    'depin.activeNodes': 'Active Nodes',
    'depin.totalRewards': 'Total Rewards',
    'depin.myNodes': 'My Nodes',
    'depin.networkOverview': 'Network Overview',
    'depin.topProjects': 'Top DePIN Projects',
    'depin.filecoin': 'Filecoin',
    'depin.filecoinDesc': 'Decentralized storage network',
    'depin.helium': 'Helium',
    'depin.heliumDesc': 'Wireless network infrastructure',
    'depin.renderNetwork': 'Render Network',
    'depin.renderDesc': 'Distributed GPU computing',
    'depin.joinNetwork': 'Join Network',
    'depin.viewDetails': 'View Details',
    'depin.storageCapacity': 'Storage Capacity',
    'depin.networkHealth': 'Network Health',
    'depin.dailyRewards': 'Daily Rewards',
    'depin.networkMap': 'Network Map',
    'depin.roiCalculator': 'ROI Calculator',
    'depin.refreshData': 'Refresh Data',
    'depin.browseNetworks': 'Browse Networks',
    'depin.calculateROI': 'Calculate ROI',
    'depin.portfolioValue': 'Portfolio Value',
    'depin.totalEarned': 'Total Earned',
    'depin.availableNetworks': 'Available networks',
    'depin.online': 'online',
    'depin.systemNotifications': 'System Notifications',
    'depin.clearAll': 'Clear All',
    'depin.hivemapperDesc': 'Decentralized mapping network with dash cams',
    'depin.akashDesc': 'Decentralized cloud computing marketplace',
    'depin.dimoDesc': 'Vehicle data network connecting cars to web3',
    'depin.weatherxmDesc': 'Decentralized weather data network',
    'depin.shadowDriveDesc': 'Solana-native decentralized storage',
    'depin.nodeMonitor': 'Node Monitor',
    'depin.performance': 'Performance',
    'depin.earnings': 'Earnings',
    'depin.hardware': 'Hardware',
    'depin.settings': 'Settings',
    'depin.configuration': 'Configuration',
    'depin.projectOverview': 'Project Overview',
    'depin.hardwareRequirements': 'Hardware Requirements',
    'depin.networkAnalytics': 'Network Analytics',
    'depin.globalNodeDistribution': 'Global Node Distribution',
    'depin.locationList': 'Location List',
    'depin.worldMap': 'World Map',
    'depin.analytics': 'Analytics',
    'depin.nodeDensity': 'Node Density',
    'depin.regionalDistribution': 'Regional Distribution',
    'depin.topPerformingCities': 'Top Performing Cities',
    'depin.networkGrowthTrends': 'Network Growth Trends',

    // DAO
    'dao.title': 'DAO',
    'dao.subtitle': 'Decentralized Autonomous Organizations',
    'dao.overview': 'Overview',
    'dao.governance': 'Governance',
    'dao.proposals': 'Proposals',
    'dao.projects': 'Projects',
    'dao.voting': 'Voting',
    'dao.treasury': 'Treasury',
    'dao.rewards': 'Rewards',
    'dao.members': 'Members',
    'dao.balance': 'Balance',
    'dao.tokenAccounts': 'Token Accounts',
    'dao.activeProposals': 'Active Proposals',
    'dao.latestActivity': 'Latest Activity',
    'dao.newProposal': 'New Proposal Created',
    'dao.newProposalDesc': 'Investment in blockchain gaming project GameFi Protocol',
    'dao.projectRewards': 'Project Rewards',
    'dao.milestoneComplete': 'Milestone Completed',
    'dao.completed': 'Completed',
    'dao.verified': 'Verified',
    'dao.createProposal': 'Create Proposal',
    'dao.joinDAO': 'Join DAO',
    'dao.proposalsDesc': 'Manage and vote on governance proposals',
    'dao.noActiveProposals': 'No Active Proposals',
    'dao.noProposalsDesc': 'Create your first proposal to get started',
    'dao.createFirstProposal': 'Create First Proposal',
    'dao.treasuryOverview': 'Treasury Overview',
    'dao.treasuryDesc': 'Manage DAO funds and allocations',
    'dao.emptyTreasury': 'Empty Treasury',
    'dao.emptyTreasuryDesc': 'Add funds to your DAO treasury',
    'dao.addFunds': 'Add Funds',
    'dao.memberManagement': 'Member Management',
    'dao.membersDesc': 'Manage DAO membership and permissions',
    'dao.noMembers': 'No Members Yet',
    'dao.noMembersDesc': 'Invite members to join your DAO',
    'dao.inviteMembers': 'Invite Members',
    'dao.totalVotes': 'Total Votes',
    'dao.treasuryValue': 'Treasury Value',
    'dao.myVotingPower': 'My Voting Power',
    'dao.recentProposals': 'Recent Proposals',
    'dao.vote': 'Vote',
    'dao.abstain': 'Abstain',
    'dao.support': 'Support',
    'dao.against': 'Against',
    'dao.proposalStatus': 'Proposal Status',
    'dao.votingEnds': 'Voting Ends',
    'dao.quorum': 'Quorum',
    'dao.participatingDAOs': 'Participating DAOs',
    'dao.investmentProposals': 'Investment Proposals',
    'dao.noDAOFound': 'No DAO Found',
    'dao.needCreateDAO': 'You need to create or join a DAO first',
    'dao.createNewDAO': 'Create New DAO',
    'dao.autoGovernanceNote': 'Creating a DAO will automatically generate governance token settings and voting parameters',
    'dao.projectsDesc': 'Manage your DAO projects and initiatives',
    'dao.projectTitle': 'Project Title',
    'dao.description': 'Description',
    'dao.addProject': 'Add Project',
    'dao.noActiveProjects': 'No Active Projects',
    'dao.treasuryManagement': 'Treasury Management',
    'dao.withdraw': 'Withdraw',
    'dao.deposit': 'Deposit',
    'dao.totalBalance': 'Total Balance',
    'dao.availableBalance': 'Available Balance',
    'dao.lockedBalance': 'Locked Balance',
    'dao.connectWalletForDetails': 'Connect wallet to view detailed transaction history',
    'dao.monthlyIncome': 'Monthly Income',
    'dao.cumulativeDistribution': 'Cumulative Distribution',
    'dao.monthlyReturn': 'Monthly Return',
    'dao.distributedMembers': 'Distributed Members',
    'dao.distributionManagement': 'Distribution Management',
    'dao.historyRecords': 'History Records',
    'dao.rewardsTrend': 'Rewards Trend',
    'dao.monthlyDistributionStatus': 'Monthly Distribution Status',
    'dao.totalIncome': 'Total Income',
    'dao.platformFee': 'Platform Fee',
    'dao.distributionAmount': 'Distribution Amount',
    'dao.participatingMembers': 'Participating Members',
    'dao.distributed': 'Distributed',
    'dao.person': 'person',
    'dao.membersList': 'Members List',
    'dao.totalMembers': 'Total Members',
    'dao.activeMembers': 'Active Members',
    'dao.totalGovernanceTokens': 'Total Governance Tokens',
    'dao.averageScore': 'Average Score',
    'dao.memberAddress': 'Member Address',
    'dao.governanceTokens': 'Governance Tokens',
    'dao.reputation': 'Reputation',
    'dao.joinTime': 'Join Time',
    'dao.actions': 'Actions',
    'dao.active': 'Active',
    'dao.inactive': 'Inactive',
    'dao.edit': 'Edit',
    'dao.remove': 'Remove',
    'dao.votingPower': 'Voting Power',
    'dao.analytics': 'Analytics',
    
    // Project Management
    'dao.projectManagement': 'Project Management',
    'dao.createProject': 'Create Project',
    'dao.projectStatus': 'Project Status',
    'dao.projectBudget': 'Project Budget',
    'dao.projectProgress': 'Project Progress',
    'dao.milestones': 'Milestones',
    'dao.milestoneStatus': 'Milestone Status',
    'dao.milestoneBudget': 'Milestone Budget',
    'dao.milestoneDeadline': 'Milestone Deadline',
    'dao.projectTeam': 'Project Team',
    'dao.projectCategory': 'Project Category',
    'dao.projectROI': 'Project ROI',
    'dao.projectRisk': 'Project Risk',
    'dao.ongoing': 'Ongoing',
    'dao.paused': 'Paused',
    'dao.low': 'Low',
    'dao.medium': 'Medium',
    'dao.high': 'High',
    'dao.pending': 'Pending',
    'dao.inProgress': 'In Progress',
    
    // Revenue Distribution
    'dao.revenueDistribution': 'Revenue Distribution',
    'dao.distributionRules': 'Distribution Rules',
    'dao.distributionHistory': 'Distribution History',
    'dao.distributionSettings': 'Distribution Settings',
    'dao.automaticDistribution': 'Automatic Distribution',
    'dao.distributionFrequency': 'Distribution Frequency',
    'dao.nextDistribution': 'Next Distribution',
    'dao.byTokenHolding': 'By Token Holding',
    'dao.byContribution': 'By Contribution',
    'dao.equalDistribution': 'Equal Distribution',
    'dao.customDistribution': 'Custom Distribution',
    'dao.distributionMethod': 'Distribution Method',
    'dao.totalDistributed': 'Total Distributed',
    'dao.yourShare': 'Your Share',
    'dao.claimRewards': 'Claim Rewards',
    'dao.rewardsClaimed': 'Rewards Claimed',
    'dao.pendingRewards': 'Pending Rewards',
    
    // Governance 
    'dao.createNewProposal': 'Create New Proposal',
    'dao.proposalTitle': 'Proposal Title',
    'dao.proposalDescription': 'Proposal Description',
    'dao.proposalCategory': 'Proposal Category',
    'dao.votingPeriod': 'Voting Period',
    'dao.quorumRequired': 'Quorum Required',
    'dao.passThreshold': 'Pass Threshold',
    'dao.proposalAmount': 'Proposal Amount',
    'dao.forVotes': 'For',
    'dao.againstVotes': 'Against',
    'dao.abstainVotes': 'Abstain',
    'dao.voteNow': 'Vote Now',
    'dao.executionStatus': 'Execution Status',
    'dao.executed': 'Executed',
    'dao.timeLeft': 'Time Left',
    'dao.votingHistory': 'Voting History',
    'dao.delegateVotes': 'Delegate Votes',
    'dao.delegatedTo': 'Delegated To',
    'dao.delegatedFrom': 'Delegated From',
    'dao.confirmVote': 'Confirm Vote',
    'dao.voteWarning': 'Your vote will be recorded on-chain and cannot be changed.',
    'dao.executeWarning': 'This will execute the proposal and transfer funds.',
    'dao.execute': 'Execute',
    'dao.proposalCreated': 'Proposal Created',
    'dao.proposalCreatedDesc': 'Your proposal has been submitted successfully',
    'dao.projectCreated': 'Project Created', 
    'dao.projectCreatedDesc': 'Your project has been created successfully',
    'dao.voteSubmitted': 'Vote Submitted',
    'dao.proposalDeleted': 'Proposal Deleted',
    'dao.projectDeleted': 'Project Deleted',
    'dao.deleteProposal': 'Delete Proposal',
    'dao.deleteProject': 'Delete Project',
    'dao.dataExported': 'Data Exported Successfully',
    'dao.dataImported': 'Data Imported Successfully',
    'dao.exportError': 'Error Exporting Data',
    'dao.importError': 'Error Importing Data',
    
    // Member Management Extended
    'dao.memberRole': 'Member Role',
    'dao.contributionScore': 'Contribution Score',
    'dao.lastActivity': 'Last Activity',
    'dao.memberSince': 'Member Since',
    'dao.proposalsCreated': 'Proposals Created',
    'dao.votingParticipation': 'Voting Participation',
    'dao.delegatedVotes': 'Delegated Votes',
    'dao.admin': 'Admin',
    'dao.member': 'Member',
    'dao.contributor': 'Contributor',
    'dao.observer': 'Observer',
    'dao.updateRole': 'Update Role',
    'dao.viewProfile': 'View Profile',
    
    // Treasury Extended
    'dao.treasuryTransactions': 'Treasury Transactions',
    'dao.transactionHistory': 'Transaction History',
    'dao.transactionType': 'Transaction Type',
    'dao.transactionAmount': 'Transaction Amount',
    'dao.transactionDate': 'Transaction Date',
    'dao.transactionHash': 'Transaction Hash',
    'dao.assetAllocation': 'Asset Allocation',
    'dao.portfolioValue': 'Portfolio Value',
    'dao.monthlyFlow': 'Monthly Flow',
    'dao.income': 'Income',
    'dao.expenses': 'Expenses',
    'dao.investment': 'Investment',
    'dao.reward': 'Reward',
    'dao.fee': 'Fee',
    'dao.milestonePayment': 'Milestone Payment',
    
    // Analytics
    'dao.daoAnalytics': 'DAO Analytics',
    'dao.performanceMetrics': 'Performance Metrics',
    'dao.memberActivity': 'Member Activity',
    'dao.proposalSuccess': 'Proposal Success Rate',
    'dao.treasuryGrowth': 'Treasury Growth',
    'dao.participationRate': 'Participation Rate',
    'dao.averageVotingTime': 'Average Voting Time',
    'dao.topContributors': 'Top Contributors',
    'dao.recentActivity': 'Recent Activity',
    'dao.activityType': 'Activity Type',
    'dao.timePeriod': 'Time Period',
    'dao.lastMonth': 'Last Month',
    'dao.last3Months': 'Last 3 Months',
    'dao.lastYear': 'Last Year',
    'dao.allTime': 'All Time',

    // Journal
    'journal.title': 'Journal',
    'journal.description': 'Document your trading thoughts, strategies, and market analysis',
    'journal.newEntry': 'New Entry',
    'journal.totalEntries': 'Total Entries',
    'journal.categories': 'Categories',
    'journal.tagsUsed': 'Tags Used',
    'journal.thisWeek': 'This Week',
  },
  zh: {
    // Navigation
    'nav.dashboard': '仪表盘',
    'nav.meme': 'Meme币',
    'nav.airdrop': '空投',
    'nav.arbitrage': '套利',
    'nav.spot': '现货',
    'nav.journal': '交易日志',
    'nav.tools': '工具',
    'nav.depin': 'DePIN',
    'nav.dao': 'DAO',
    
    // Common
    'common.appTitle': 'Web3看板',
    'common.connectWallet': '连接钱包',
    'common.connected': '已连接',
    'common.loading': '加载中...',
    'common.search': '搜索',
    'common.filter': '筛选',
    'common.new': '新建',
    'common.edit': '编辑',
    'common.delete': '删除',
    'common.save': '保存',
    'common.cancel': '取消',
    'common.confirm': '确认',
    'common.required': '必填',
    'common.invalidAmount': '金额无效',
    'common.invalidPeriod': '周期无效',
    'common.invalidQuorum': '法定人数无效',
    'common.invalidThreshold': '通过门槛必须在50-100%之间',
    'common.confirmDelete': '确认删除',
    'common.deleteWarning': '此操作不能撤销，您确定吗？',
    'common.confirmCancel': '确认取消',
    'common.cancelWarning': '您确定要取消吗？未保存的更改将丢失。',
    'common.actionWarning': '您确定要继续吗？',
    
    // Dashboard
    'dashboard.title': '仪表盘',
    'dashboard.subtitle': '欢迎来到您的Web3交易中心。监控市场，追踪空投，管理您的投资组合。',
    'dashboard.totalPortfolio': '投资组合总价值',
    'dashboard.memeCoinsTracked': '追踪的Meme币',
    'dashboard.activeAirdrops': '活跃空投',
    'dashboard.arbitrageOpportunities': '套利机会',
    'dashboard.marketOverview': '市场概览',
    'dashboard.marketOverviewDesc': '实时价格变动和趋势',
    'dashboard.chartPlaceholder': '图表可视化将在此实现',
    'dashboard.quickActions': '快速操作',
    'dashboard.quickActionsDesc': '快速访问常用任务',
    'dashboard.checkAirdrops': '检查空投',
    'dashboard.pendingAirdrops': '8个待处理',
    'dashboard.viewMemeTrends': '查看Meme趋势',
    'dashboard.memeTracked': '已追踪142个',
    'dashboard.arbitrageScanner': '套利扫描器',
    'dashboard.arbitrageOpportunitiesCount': '3个机会',
    
    // Meme
    'meme.title': 'Meme币',
    'meme.subtitle': '追踪热门Meme币并发现新机会',
    'meme.watchlist': '关注列表',
    'meme.discoverNew': '发现新币',
    'meme.marketSummary': '市场概览',
    'meme.totalMarketCap': '总市值',
    'meme.volume24h': '24小时交易量',
    'meme.trendingCoins': '热门币种',
    'meme.alerts': '提醒',
    'meme.addToWatchlist': '添加币种到关注列表',
    'meme.setPriceAlerts': '设置价格提醒',
    'meme.trendingMemeCoins': '热门Meme币',
    'meme.mostPopular': '按交易量和社交活跃度排序的最受欢迎Meme币',
    'meme.marketCap': '市值',
    'meme.volume': '交易量',

    // Airdrop
    'airdrop.title': '空投',
    'airdrop.subtitle': '追踪活跃空投并领取奖励',
    'airdrop.active': '活跃',
    'airdrop.upcoming': '即将到来',
    'airdrop.claimed': '已领取',
    'airdrop.activeAirdrops': '活跃空投',
    'airdrop.upcomingAirdrops': '即将到来的空投',
    'airdrop.claimedRewards': '已领取奖励',
    'airdrop.totalValue': '总价值',
    'airdrop.thisMonth': '本月',
    'airdrop.checkEligibility': '检查资格',
    'airdrop.claimNow': '立即领取',
    'airdrop.eligibilityChecker': '资格检查器',
    'airdrop.checkEligibilityDesc': '验证您对活跃空投的资格',
    'airdrop.endsIn': '结束于',
    'airdrop.status': '状态',
    'airdrop.rewards': '奖励',

    // Arbitrage
    'arbitrage.title': '套利',
    'arbitrage.subtitle': '在各个DEX中发现有利可图的套利机会',
    'arbitrage.scanner': '扫描器',
    'arbitrage.opportunities': '机会',
    'arbitrage.settings': '设置',
    'arbitrage.activeOpportunities': '活跃机会',
    'arbitrage.profitPotential': '盈利潜力',
    'arbitrage.executionTime': '执行时间',
    'arbitrage.tradingPairs': '交易对',
    'arbitrage.gasEstimate': 'Gas估算',
    'arbitrage.execute': '执行',
    'arbitrage.analyze': '分析',
    'arbitrage.profit': '利润',
    'arbitrage.risk': '风险',
    'arbitrage.dex': 'DEX',

    // Spot
    'spot.title': '现货交易',
    'spot.subtitle': '跨多个交易所的实时现货交易',
    'spot.buy': '买入',
    'spot.sell': '卖出',
    'spot.orderBook': '订单簿',
    'spot.recentTrades': '最近交易',
    'spot.portfolio': '投资组合',
    'spot.balance': '余额',
    'spot.available': '可用',
    'spot.inOrders': '订单中',
    'spot.marketPrice': '市价',
    'spot.limitPrice': '限价',
    'spot.amount': '数量',
    'spot.total': '总计',
    'spot.placeOrder': '下单',
    'spot.openOrders': '待成交订单',
    'spot.orderHistory': '订单历史',

    // Tools
    'tools.title': '工具',
    'tools.subtitle': '综合Web3交易工具和实用程序',
    'tools.priceAlerts': '价格提醒',
    'tools.portfolio': '投资组合跟踪器',
    'tools.calculator': '计算器',
    'tools.news': '新闻与分析',
    'tools.calendar': '事件日历',
    'tools.research': '研究',
    'tools.setPriceAlert': '设置价格提醒',
    'tools.trackPortfolio': '跟踪投资组合',
    'tools.calculate': '计算',
    'tools.readNews': '阅读新闻',
    'tools.viewCalendar': '查看日历',
    'tools.doResearch': '进行研究',
    'tools.comingSoon': '即将推出',
    'tools.toolInDevelopment': '此工具正在开发中',
    
    // Tool Categories
    'tools.funding': '融资情报',
    'tools.fundingDesc': 'VC 数据、融资轮次和投资者分析',
    'tools.efficiency': '效率工具',
    'tools.efficiencyDesc': '批量操作、钱包管理和自动化',
    'tools.solana': 'Solana 工具',
    'tools.solanaDesc': 'SPL 代币、NFT 和程序实用工具',
    'tools.market': '市场数据',
    'tools.marketDesc': '价格监控、套利和流动性分析',
    'tools.security': '安全工具',
    'tools.securityDesc': '合约审计、钱包安全和风险评估',
    'tools.developer': '开发者工具',
    'tools.developerDesc': 'Anchor 模板、RPC 测试和调试',
    
    // Tool Status
    'tools.active': '可用',
    'tools.beta': '测试版',
    'tools.soon': '即将推出',
    'tools.available': '可用',
    'tools.favorites': '收藏',
    'tools.recentlyUsed': '最近使用',
    'tools.usage': '使用次数',
    'tools.open': '打开',
    'tools.use': '使用工具',

    // DePIN
    'depin.title': 'DePIN',
    'depin.subtitle': '去中心化物理基础设施网络',
    'depin.storage': '存储网络',
    'depin.computing': '计算网络',
    'depin.wireless': '无线网络',
    'depin.sensors': '传感器网络',
    'depin.totalNetworks': '总网络数',
    'depin.activeNodes': '活跃节点',
    'depin.totalRewards': '总奖励',
    'depin.myNodes': '我的节点',
    'depin.networkOverview': '网络概览',
    'depin.topProjects': '顶级DePIN项目',
    'depin.filecoin': 'Filecoin',
    'depin.filecoinDesc': '去中心化存储网络',
    'depin.helium': 'Helium',
    'depin.heliumDesc': '无线网络基础设施',
    'depin.renderNetwork': 'Render Network',
    'depin.renderDesc': '分布式GPU计算',
    'depin.joinNetwork': '加入网络',
    'depin.viewDetails': '查看详情',
    'depin.storageCapacity': '存储容量',
    'depin.networkHealth': '网络健康度',
    'depin.dailyRewards': '每日奖励',
    'depin.networkMap': '网络地图',
    'depin.roiCalculator': 'ROI计算器',
    'depin.refreshData': '刷新数据',
    'depin.browseNetworks': '浏览网络',
    'depin.calculateROI': '计算ROI',
    'depin.portfolioValue': '投资组合价值',
    'depin.totalEarned': '累计收益',
    'depin.availableNetworks': '可用网络',
    'depin.online': '在线',
    'depin.systemNotifications': '系统通知',
    'depin.clearAll': '清除全部',
    'depin.hivemapperDesc': '基于行车记录仪的去中心化地图网络',
    'depin.akashDesc': '去中心化云计算市场',
    'depin.dimoDesc': '连接汽车与Web3的车联网数据网络',
    'depin.weatherxmDesc': '去中心化气象数据网络',
    'depin.shadowDriveDesc': 'Solana原生去中心化存储',
    'depin.nodeMonitor': '节点监控',
    'depin.performance': '性能',
    'depin.earnings': '收益',
    'depin.hardware': '硬件',
    'depin.settings': '设置',
    'depin.configuration': '配置',
    'depin.projectOverview': '项目概览',
    'depin.hardwareRequirements': '硬件要求',
    'depin.networkAnalytics': '网络分析',
    'depin.globalNodeDistribution': '全球节点分布',
    'depin.locationList': '位置列表',
    'depin.worldMap': '世界地图',
    'depin.analytics': '分析',
    'depin.nodeDensity': '节点密度',
    'depin.regionalDistribution': '区域分布',
    'depin.topPerformingCities': '表现最佳城市',
    'depin.networkGrowthTrends': '网络增长趋势',

    // DAO
    'dao.title': 'DAO',
    'dao.subtitle': '去中心化自治组织',
    'dao.overview': '概览',
    'dao.governance': '治理',
    'dao.proposals': '提案',
    'dao.projects': '项目',
    'dao.voting': '投票',
    'dao.treasury': '金库',
    'dao.rewards': '收益',
    'dao.members': '成员',
    'dao.balance': '余额',
    'dao.tokenAccounts': '代币账户',
    'dao.activeProposals': '活跃提案',
    'dao.latestActivity': '最新活动',
    'dao.newProposal': '新提案创建',
    'dao.newProposalDesc': '投资区块链游戏项目 GameFi Protocol',
    'dao.projectRewards': '项目收益',
    'dao.milestoneComplete': '里程碑完成',
    'dao.completed': '已完成',
    'dao.verified': '已验证',
    'dao.createProposal': '创建提案',
    'dao.joinDAO': '加入DAO',
    'dao.proposalsDesc': '管理和投票治理提案',
    'dao.noActiveProposals': '暂无活跃提案',
    'dao.noProposalsDesc': '创建您的第一个提案开始',
    'dao.createFirstProposal': '创建首个提案',
    'dao.treasuryOverview': '金库概览',
    'dao.treasuryDesc': '管理DAO资金和分配',
    'dao.emptyTreasury': '金库为空',
    'dao.emptyTreasuryDesc': '向您的DAO金库添加资金',
    'dao.addFunds': '添加资金',
    'dao.memberManagement': '成员管理',
    'dao.membersDesc': '管理DAO成员资格和权限',
    'dao.noMembers': '暂无成员',
    'dao.noMembersDesc': '邀请成员加入您的DAO',
    'dao.inviteMembers': '邀请成员',
    'dao.totalVotes': '总投票数',
    'dao.treasuryValue': '金库价值',
    'dao.myVotingPower': '我的投票权',
    'dao.recentProposals': '最近提案',
    'dao.vote': '投票',
    'dao.abstain': '弃权',
    'dao.support': '支持',
    'dao.against': '反对',
    'dao.proposalStatus': '提案状态',
    'dao.votingEnds': '投票截止',
    'dao.quorum': '法定人数',
    'dao.participatingDAOs': '参与的DAO',
    'dao.investmentProposals': '投资提案',
    'dao.noDAOFound': '未找到DAO',
    'dao.needCreateDAO': '您需要先创建或加入DAO',
    'dao.createNewDAO': '创建新DAO',
    'dao.autoGovernanceNote': '创建DAO将自动生成治理代币设置和投票参数',
    'dao.addProject': '添加项目',
    'dao.projectTitle': '项目标题',
    'dao.description': '描述',
    'dao.noActiveProjects': '暂无活跃项目',
    'dao.treasuryManagement': '金库管理',
    'dao.withdraw': '提取',
    'dao.deposit': '存入',
    'dao.totalBalance': '总余额',
    'dao.availableBalance': '可用余额',
    'dao.lockedBalance': '锁定余额',
    'dao.connectWalletForDetails': '连接钱包查看详细交易历史',
    'dao.monthlyIncome': '月收入',
    'dao.cumulativeDistribution': '累计分配',
    'dao.monthlyReturn': '月回报',
    'dao.distributedMembers': '分配成员',
    'dao.distributionManagement': '分配管理',
    'dao.historyRecords': '历史记录',
    'dao.rewardsTrend': '收益趋势',
    'dao.monthlyDistributionStatus': '月度分配状态',
    'dao.totalIncome': '总收入',
    'dao.platformFee': '平台费用',
    'dao.distributionAmount': '分配金额',
    'dao.participatingMembers': '参与成员',
    'dao.distributed': '已分配',
    'dao.person': '人',
    'dao.membersList': '成员列表',
    'dao.totalMembers': '总成员数',
    'dao.activeMembers': '活跃成员',
    'dao.totalGovernanceTokens': '总治理代币',
    'dao.averageScore': '平均评分',
    'dao.memberAddress': '成员地址',
    'dao.governanceTokens': '治理代币',
    'dao.reputation': '声誉',
    'dao.joinTime': '加入时间',
    'dao.actions': '操作',
    'dao.active': '活跃',
    'dao.inactive': '不活跃',
    'dao.edit': '编辑',
    'dao.remove': '移除',
    'dao.votingPower': '投票权',
    'dao.analytics': '分析',
    
    // Project Management
    'dao.projectManagement': '项目管理',
    'dao.createProject': '创建项目',
    'dao.projectStatus': '项目状态',
    'dao.projectBudget': '项目预算',
    'dao.projectProgress': '项目进度',
    'dao.milestones': '里程碑',
    'dao.milestoneStatus': '里程碑状态',
    'dao.milestoneBudget': '里程碑预算',
    'dao.milestoneDeadline': '里程碑截止日期',
    'dao.projectTeam': '项目团队',
    'dao.projectCategory': '项目类别',
    'dao.projectROI': '项目投资回报率',
    'dao.projectRisk': '项目风险',
    'dao.ongoing': '进行中',
    'dao.paused': '已暂停',
    'dao.low': '低',
    'dao.medium': '中',
    'dao.high': '高',
    'dao.pending': '待处理',
    'dao.inProgress': '进行中',
    
    // Revenue Distribution
    'dao.revenueDistribution': '收益分配',
    'dao.distributionRules': '分配规则',
    'dao.distributionHistory': '分配历史',
    'dao.distributionSettings': '分配设置',
    'dao.automaticDistribution': '自动分配',
    'dao.distributionFrequency': '分配频率',
    'dao.nextDistribution': '下次分配',
    'dao.byTokenHolding': '按持币比例',
    'dao.byContribution': '按贡献度',
    'dao.equalDistribution': '平均分配',
    'dao.customDistribution': '自定义分配',
    'dao.distributionMethod': '分配方式',
    'dao.totalDistributed': '总分配量',
    'dao.yourShare': '您的份额',
    'dao.claimRewards': '领取奖励',
    'dao.rewardsClaimed': '已领取奖励',
    'dao.pendingRewards': '待领取奖励',
    
    // Governance 
    'dao.createNewProposal': '创建新提案',
    'dao.proposalTitle': '提案标题',
    'dao.proposalDescription': '提案描述',
    'dao.proposalCategory': '提案类别',
    'dao.votingPeriod': '投票期间',
    'dao.quorumRequired': '所需法定人数',
    'dao.passThreshold': '通过门槛',
    'dao.proposalAmount': '提案金额',
    'dao.forVotes': '支持票',
    'dao.againstVotes': '反对票',
    'dao.abstainVotes': '弃权票',
    'dao.voteNow': '立即投票',
    'dao.executionStatus': '执行状态',
    'dao.executed': '已执行',
    'dao.timeLeft': '剩余时间',
    'dao.votingHistory': '投票历史',
    'dao.delegateVotes': '委托投票',
    'dao.delegatedTo': '委托给',
    'dao.delegatedFrom': '委托来自',
    'dao.confirmVote': '确认投票',
    'dao.voteWarning': '您的投票将记录在链上且无法更改。',
    'dao.executeWarning': '这将执行提案并转移资金。',
    'dao.execute': '执行',
    'dao.proposalCreated': '提案已创建',
    'dao.proposalCreatedDesc': '您的提案已成功提交',
    'dao.projectCreated': '项目已创建',
    'dao.projectCreatedDesc': '您的项目已成功创建',
    'dao.voteSubmitted': '投票已提交',
    'dao.proposalDeleted': '提案已删除',
    'dao.projectDeleted': '项目已删除',
    'dao.deleteProposal': '删除提案',
    'dao.deleteProject': '删除项目',
    'dao.dataExported': '数据导出成功',
    'dao.dataImported': '数据导入成功',
    'dao.exportError': '数据导出错误',
    'dao.importError': '数据导入错误',
    
    // Member Management Extended
    'dao.memberRole': '成员角色',
    'dao.contributionScore': '贡献分数',
    'dao.lastActivity': '最后活动',
    'dao.memberSince': '成员加入时间',
    'dao.proposalsCreated': '创建的提案',
    'dao.votingParticipation': '投票参与度',
    'dao.delegatedVotes': '委托投票',
    'dao.admin': '管理员',
    'dao.member': '成员',
    'dao.contributor': '贡献者',
    'dao.observer': '观察者',
    'dao.updateRole': '更新角色',
    'dao.viewProfile': '查看档案',
    
    // Treasury Extended
    'dao.treasuryTransactions': '金库交易',
    'dao.transactionHistory': '交易历史',
    'dao.transactionType': '交易类型',
    'dao.transactionAmount': '交易金额',
    'dao.transactionDate': '交易日期',
    'dao.transactionHash': '交易哈希',
    'dao.assetAllocation': '资产配置',
    'dao.portfolioValue': '投资组合价值',
    'dao.monthlyFlow': '月度现金流',
    'dao.income': '收入',
    'dao.expenses': '支出',
    'dao.investment': '投资',
    'dao.reward': '奖励',
    'dao.fee': '费用',
    'dao.milestonePayment': '里程碑付款',
    
    // Analytics
    'dao.daoAnalytics': 'DAO分析',
    'dao.performanceMetrics': '性能指标',
    'dao.memberActivity': '成员活动',
    'dao.proposalSuccess': '提案成功率',
    'dao.treasuryGrowth': '金库增长',
    'dao.participationRate': '参与率',
    'dao.averageVotingTime': '平均投票时间',
    'dao.topContributors': '顶级贡献者',
    'dao.recentActivity': '近期活动',
    'dao.activityType': '活动类型',
    'dao.timePeriod': '时间段',
    'dao.lastMonth': '上个月',
    'dao.last3Months': '最近3个月',
    'dao.lastYear': '去年',
    'dao.allTime': '全部时间',

    // Journal
    'journal.title': '交易日志',
    'journal.description': '记录您的交易思路、策略和市场分析',
    'journal.newEntry': '新建日志',
    'journal.totalEntries': '日志总数',
    'journal.categories': '分类',
    'journal.tagsUsed': '使用标签',
    'journal.thisWeek': '本周',
  }
}

export const LanguageContext = createContext<LanguageContextType | undefined>(undefined)

export function useLanguage() {
  const context = useContext(LanguageContext)
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider')
  }
  return context
}

export function useLanguageState() {
  const [language, setLanguageState] = useState<Language>('en')

  useEffect(() => {
    const stored = localStorage.getItem('language') as Language
    if (stored && (stored === 'en' || stored === 'zh')) {
      setLanguageState(stored)
    }
  }, [])

  const setLanguage = (lang: Language) => {
    setLanguageState(lang)
    localStorage.setItem('language', lang)
  }

  const t = (key: string) => {
    return translations[language][key as keyof typeof translations['en']] || key
  }

  return { language, setLanguage, t }
}